### ISSUE TITLE
搜索文字下移

### ISSUE THREAD

**Issue by LQC-WoW** [CCY0122/WanAndroid_Flutter#10]
如题，始终觉得跨端开发和原生有一定差距，实现效果整体感觉没有原生的舒服
![微信图片_20200415094848](https://user-images.githubusercontent.com/34181091/79290453-badc1580-7efe-11ea-8b01-71edf0f96509.jpg)

**Comment by CCY0122** [comment]
1、flutter某个版本起把文字框padding逻辑改动了，导致原本居中的写法变成偏下。我之前把首页的给适配了，但忘记适配搜索页的了。
2、感觉确实有点不一样，比如列表滑动手感和原生的不一样，不过flutter未来会越来越好的，该学还是要学
