### ISSUE TITLE
怎么感觉主页-项目的滑动有点晃眼

### ISSUE THREAD

**Issue by debughao** [CCY0122/WanAndroid_Flutter#5]
主页-项目页滑动的时候页面有点抖动的感觉，不是很流畅。感觉很耗内存的样子。如下图：整个应用都占了400多M
![Screenshot_2019-08-23-10-22-27-421_com miui secur](https://user-images.githubusercontent.com/10276104/63562368-f13fdb80-c58f-11e9-8efa-4bc0bd9cf170.png)

**Comment by CCY0122** [comment]
请问你装的是从主页下载的release版本还是自己编译的debug版？
如果是debug版，这是正常现象，flutter为了debug版能够热重载等功能就是会比较卡顿、 占内存。
如果是release版。。那我需要排查一下
