### ISSUE TITLE
卡顿问题

### ISSUE THREAD

**Issue by ArrayTeng** [CCY0122/WanAndroid_Flutter#6]
我试用“玩儿Android”，界面UI非常漂亮，但就是滑动的时候感觉“卡卡”的，没那么润滑的感觉，尤其是在文章详情页面非常的卡，上下滑动得要等个 1 秒才能响应，我用的是Vivo手机，Android8.1.0版本

**Comment by CCY0122** [comment]
请问是release版还是debug版

**Comment by ArrayTeng** [comment]
扫二维码下载的，应该是 release版 的，我同样下载了 flutter go，发现他们的详情页面也卡
