### ISSUE TITLE
求教！flutter 最新的版本，master，不能编译运行

### ISSUE THREAD

**Issue by Crazy-MT** [CCY0122/WanAndroid_Flutter#8]
解决了 Android X 的问题，解决了一些库版本低的问题。

**Comment by CCY0122** [comment]
感谢反馈。
现已更新了flutter环境，更新了部分依赖库，将android端适配为androidX并更新了gradle版本以解决部分库兼容问题。

**Comment by Crazy-MT** [comment]
谢谢
