### ISSUE TITLE
iOS 支持吗

### ISSUE THREAD

**Issue by yasencoder** [CCY0122/WanAndroid_Flutter#9]

**Comment by yasencoder** [comment]
iphone安装后，显示空白页面

**Comment by CCY0122** [comment]
支持的，之前测过iOS，我目前不方便调试iOS。可能是flutter环境不一致导致，你尝试下切beta分支1.7.8以上

**Comment by CCY0122** [comment]
> iphone安装后，显示空白页面

flutter版本在较高版本上（具体不知，至少1.7+），个别初始化的逻辑若在runApp之前的话，需先`WidgetsFlutterBinding.ensureInitialized()`，否则报错导致没执行runApp，app界面就一直处于启动屏状态，由于iOS端没有配置启动屏图片，所以一直空白。
现已更新flutter环境并做了修复，烦请验证你的问题是否得到解决，感谢。
